### ISSUE TITLE
Add log level features to opensds

### ISSUE THREAD

**Issue by xxwjj** [opensds/opensds#46]
OpenSDS log system is so poor,we just using printing string to diff log level. 

We could have referenced k8s's way and implemented it using  [glog](https://github.com/golang/glog).

**Comment by leonwanghui** [comment]
Yes you are right, that is definitely something we should do. Besides glog, I think [logrus](https://github.com/sirupsen/logrus) is also a good choice.

BTW, @xxwjj can you add it on our weekly meeting [agenda](https://docs.google.com/document/d/1OKDp7iDw_l_5kGyniqTKtrwRFAZMvItGghsxfrCqr5c/edit#) so that we can discuss it on the next weekly meeting?

**Comment by xxwjj** [comment]
ok

**Comment by leonwanghui** [comment]
This Issue will be closed, for its referenced [PR](https://github.com/opensds/opensds/pull/74) has been merged.
