### ISSUE TITLE
Add global config support

### ISSUE THREAD

**Issue by wisererik** [opensds/opensds#59]
**Is this a BUG REPORT or FEATURE REQUEST?**:

help wanted

**What you expected to happen**:

I found that the command tools start up opensds project by reading the command-line options and by setting up the configuration of servers, databases, etc.  IMO, the command-line options are not the best choice when more and more configuration options are required. There is an another way to manage configuration  by reading and parsing the specified configuration file into  a global golang structure. The configuration structure may look like:
```
type Config struct{
    Server ServerConfig
    DB DBConfig
    Log LogConfig
}

type ServerConfig struct{
    Host string
    Port int
    ReadTimeOut int
    WriteTimeOut int
   // ......
}

type DBConfig struct{}

type LogConfig struct{}
```

**Comment by leonwanghui** [comment]
Sounds a good idea. Some popular projects such like kubernetes, support initializing configuration from files. IMO, it would be good if we could define a unified ```Config``` object containing all parameters required, and parse it in the form of json or yaml.

@wisererik Could you finish the code development so that we can better understand? And last but not least, plz don't forget the testing code :p

**Comment by wisererik** [comment]
@leonwanghui my pleasure~

**Comment by leonwanghui** [comment]
Plz see PR [#65](https://github.com/opensds/opensds/pull/65) for development.

**Comment by leonwanghui** [comment]
Also see [#82](https://github.com/opensds/opensds/pull/82) and [#75](https://github.com/opensds/opensds/pull/75)
