### ISSUE TITLE
How can I get profile details in my storage driver for OpenSDS

### ISSUE THREAD

**Issue by fideltak** [opensds/opensds#686]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
I need to get profile details in my storage driver for OpenSDS.
It looks we can get profile ID only by using pb.CreateVolumeOpts.GetProfileId.
Is there easy way to get contents in profiles for getting storage specific values in "customProperties"?
This request is related this [issue](https://github.com/opensds/opensds/issues/642).

**What you expected to happen**:
be able to get profile details in storage driver code when creating volumes.
**How to reproduce it (as minimally and precisely as possible)**:
**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Hi @fideltak ,I thought we have added profile details in `pb.CreateVolumeOpts` and `pb.DeleteVolumeOpts`, you can fetch it using `pb.CreateVolumeOpts.GetProfile()`.

**Comment by xing-yang** [comment]
Hi @fideltak This issue should have been fixed by this PR: https://github.com/opensds/opensds/pull/648.  There is an example in that PR describing how to get customProperties of a profile.

A "profile" parameter is added to CreateVolumeOpts.  So you should be able to get the profile by pb.CreateVolumeOpts.GetProfile().  The "profileId" field is still there but we will remove it in the future.

See here: https://github.com/opensds/opensds/blob/development/pkg/model/proto/model.proto#L177

Are you using code from the latest development branch?

**Comment by fideltak** [comment]
@xing-yang , @leonwanghui I missed it... Thank you for your support!!

**Comment by xing-yang** [comment]
@fideltak You are welcome!  Thanks for working on the driver!
