### ISSUE TITLE
FileShare-DashBoard: Access Creation allowing duplicate rules

### ISSUE THREAD

**Issue by satya-gorli** [opensds/opensds#927]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
 /kind feature

**What happened**:
1. Create file share and ensure the file share is in available state
2. Create Access... popup opens
3. Give IP as 12.12.12.12/12 (infact any ip)
4. Select add rule.. and provide same IP 
or
Create new Access with same IP
System is allowing
**What you expected to happen**:
No Duplicate IP should be allowed in Access.
![FileShareDashBoard_ Access creation allowing duplicate Rules](https://user-images.githubusercontent.com/48289385/60085755-8290fe00-9757-11e9-9b72-a40367d25034.PNG)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rhsakarpos** [comment]
AFAIU, this is a fix to NOT allow duplicate IPs in fileshare rules....my $0.02

1. this has to be backend API behavior
2. same behaviour is applicable to any user of the API, not just UI...if a duplicate IP is found in a addRule call, the backend should return the existing rule for that IP (if any), so user can leave it as is OR delete existing rule (by calling another API) and then add the new rule for the same IP (which is now non-deuplicate)
2. please make the add rule on the UI atomic. each OK from the user, for each rule, can
2a. make a backend call to addRule
2.b make a backend call to getAllRules (to refresh the UI with the newly added rule)
3. UI should ideally NOT have any interim state, since these get very tricky to hanlde in a multi user concurrent usage of the same page scenarios. 
4. the fact that we cannot have duplicate rules with same IP, is a domain rule, This should be enforced by backedn API, NOT in UI.

**Comment by PravinRanjan10** [comment]
![defect4](https://user-images.githubusercontent.com/41313813/71620313-4ac7af00-2bef-11ea-8902-49f98e42dc92.png)
It's Fixed. Verified the validation. SO closing this. This has been fix by PR #178
